apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: my-test2-antk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: my-test2-antk
    app.kubernetes.io/part-of: my-test2-1
  name: my-test2-antk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: my-test2-antk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: my-test2-antk
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/mkosiarc-tenant/my-test2-1/my-test2-antk@sha256:7f01c83e6cce875c6c552851cbb59dfdca8861fb41fffffbe9f39f1d8bbb283f
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
